name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up known hosts
        run: |
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH and deploy
        run: |
          ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} "
            echo 'Changing directory...'
            cd lightsail-practice  || { echo 'Directory lightsail-practice not found'; exit 1; }
            echo 'Resetting local changes...'
            git reset --hard HEAD || exit 1
            echo 'Pulling latest code with automatic conflict resolution...'
            git pull -X ours origin dev || exit 1  # Automatically resolve conflicts by favoring local changes
            echo 'Installing npm dependencies...'
            npm install || exit 1
            echo 'Building project...'
            npm run build || exit 1
            echo 'Stopping existing node processes...'
            sudo pkill node
            echo 'Starting the application...'
            sudo npm run start > server.log 2>&1 &  # Run server in background but keep session open
            echo 'Waiting for the server to start...'
            npx wait-on http://localhost || { echo 'Server did not start'; exit 1; }
            echo 'Server is up and running!'
            echo 'Exiting...'
            exit
          "
